### ISSUE TITLE
Display the plugin menus in categories

### ISSUE THREAD

**Issue by fengzhenbing** [apache/incubator-shenyu-dashboard#125]
Task

- [x] Add some category menu under the plugin list menu.
- [x] Put the plugin menu in order under each category menu.
- [x] Menu permission function remains unchanged

The current plugin list menu style is as follows, in order to facilitate users to find plugins, we need display the plugin menus in categories.
![image](https://user-images.githubusercontent.com/4169359/122560945-cf242100-d073-11eb-9c31-310985e2586e.png)

**Comment by daiwenyu** [comment]
I can do it
