### ISSUE TITLE
user can not modify password

### ISSUE THREAD

**Issue by qicz** [apache/incubator-shenyu-dashboard#160]
the user with user modify user role, but can not modify anything.

![1638354484(1)](https://user-images.githubusercontent.com/2174082/144218273-58ae9d34-f49f-4f90-b1cf-5b6215f903b7.jpg)
![1638354546(1)](https://user-images.githubusercontent.com/2174082/144218274-0ab78a01-329d-4c47-9463-1104064e1bb2.jpg)

**Comment by daiwenyu** [comment]
I'll fix it

**Comment by daiwenyu** [comment]
@qicz 

Please release the interface

/dashboardUser?currentPage=1&pageSize=12

**Comment by daiwenyu** [comment]
@qicz Please close this issue
