### ISSUE TITLE
support "Configure Data Permission" search

### ISSUE THREAD

**Issue by qicz** [apache/incubator-shenyu-dashboard#164]
search the selector in "Configure Data Permission" pop
![image](https://user-images.githubusercontent.com/2174082/145342191-9de9e1dc-35ee-41d2-bb13-150885bf0585.png)

**Comment by daiwenyu** [comment]
I'll deal with it

**Comment by daiwenyu** [comment]
新增查询和分类
![image](https://user-images.githubusercontent.com/16659386/147049490-c17fc657-07d5-4611-9fd7-078fd95d6683.png)
