### ISSUE TITLE
<Bug>There are some paging bugs in the addition and modification of the AppAuth

### ISSUE THREAD

**Issue by OnlyQuiet** [apache/incubator-shenyu-dashboard#174]
version: master

1、Delete one, but delete all
![image](https://user-images.githubusercontent.com/41868553/147809942-382dbdf5-e048-4233-94c9-86ba77bd9cb2.png)
![image](https://user-images.githubusercontent.com/41868553/147809952-eb7e393e-740c-4eba-a36c-2346a5bebab3.png)

2、Pagination cannot be switched
![image](https://user-images.githubusercontent.com/41868553/147809859-3c5d333e-5633-41d4-8569-b85e00476ba3.png)

**Comment by OnlyQuiet** [comment]
Can i fix them?

**Comment by yu199195** [comment]
you can try @OnlyQuiet
