### ISSUE TITLE
some time login can not show menu

### ISSUE THREAD

**Issue by qicz** [apache/incubator-shenyu-dashboard#179]
![de8ec60f91382efe84d5cb442177f52](https://user-images.githubusercontent.com/2174082/149280924-b7c44b22-5d75-4188-a6d5-8c92c9e970ad.png)

**Comment by daiwenyu** [comment]
i can fix it

**Comment by daiwenyu** [comment]
Sorry, Cannot reproduce @qicz

**Comment by daiwenyu** [comment]
There is no problem for a long time. If it occurs again, create a new issue, thank you
