### ISSUE TITLE
[Question] There seems to be a bug in the login function

### ISSUE THREAD

**Issue by erdengk** [apache/incubator-shenyu-dashboard#184]
### Question

I'm a newbie and I want to contribute to shenyu. So I downloaded the code (v2.4.2) and ran it in idea.

I'm not familiar with shenyu, so I don't know how to describe this bug. I also found this bug by accident.

Steps to reproduce.
1. Run shenyu
2. Since I have logged in shenyu before, the browser saves the address
![image](https://user-images.githubusercontent.com/37730787/154851509-32feb769-fd4e-4a24-af16-d062058ac557.png)
3. I went directly to this URL and there was an error message in the upper right corner.
http://localhost:9095/#/home
![image](https://user-images.githubusercontent.com/37730787/154851527-605f7d78-4ece-4c25-a594-4eee1842c520.png)

4. I entered the admin account and password and clicked login in. The toolbar on the left is gone.This is a screenshot of the browser console.
![image](https://user-images.githubusercontent.com/37730787/154851573-709ba32b-0912-4401-8020-b2e7bdbfcd0e.png)

5. When I refresh, the toolbar on the left reappears. The console also has no error messages.
![image](https://user-images.githubusercontent.com/37730787/154851470-a7bf3d72-a438-4139-8e89-6e54bb5c7145.png)

I thought it happened by accident, but I was able to reproduce the problem every time with the steps above. I also tested that after running shenyu, visit http://localhost:9095, so that the problem of the above toolbar disappearing will not occur.

Generally speaking, users who visit the page directly without logging in will be blocked, which is the correct operation. But after the user enters the correct account password to log in, they should see the correct page.

The above is my opinion, if you have other questions, please @erdengk

**Comment by JooKS-me** [comment]
> Hi, @JooKS-me I would like to work on this bug. Can you assign this to me?

Good luck~

By the way, the problem might be in [incubator-shenyu-dashboard](https://github.com/apache/incubator-shenyu-dashboard), so I transferred the issue to here.

**Comment by kaveeshadinamidu** [comment]
Hey, @JooKS-me I think I found the issue. When redirecting to the http://localhost:9095/#/home it executes the componentDidMount() function at Home/index.js

```
componentDidMount() {
    const { dispatch } = this.props;
    dispatch({
      type: "global/fetchPlatform"
    });
  }
```
When the user do not have a token the API call fetchPlatfrom responds with an error message. `{"code":600,"message":"token is error"}` 

And then the componentDidMount() method at layouts/BasicLayout.js executes. 
```
componentDidMount() {
    const token = window.sessionStorage.getItem("token");
    if (!token) {
      this.props.history.push({
        pathname: "/user/login"
      });
      return;
    }
    const { dispatch } = this.props;
    dispatch({
      type: "global/fetchPlatform"
    });
    dispatch({
      type: "global/fetchPlugins",
      payload: {
        callback: () => {
          this.setState({
            pluginsLoaded: true
          });
        }
      }
    });
  }
```
Here it checks the availability of token and redirects them back to the login page if there is no token.
Therefore when the home page componentDidMount() method executes (When redirecting directly to http://localhost:9095/#/home ) it executes an unauthorized API call and returns it with an error. So we need to check whether the user is authorized or not before making that request on the home page.

By working around the code I have found two ways to resolve this error,

1) Suggestion 1 - Check whether the user is validated before making the API request
Changing the componentDidMount() on src/routes/Home/index.js 
Whenever the home page renders it always checks for the availability of token and made the request.
 
on src/routes/Home/index.js
```
componentDidMount() {
    const token = window.sessionStorage.getItem("token");
    if (token) {
      const { dispatch } = this.props;
      dispatch({
        type: "global/fetchPlatform"
      });
    }
  }
```

2) Suggestion two - Simply removing the componentDidMount() method on src/routes/Home/index.js 
When the home page is rendering the BasicLayout is also rendered.So both componentDidMount() methods executes. And in the basic layout's componentDidMount() method contains the same logic which is on the home page's componentDidMount() method also.
This method also works fine.

**Comment by JooKS-me** [comment]
@daiwenyu @fengzhenbing , Please take a look here :)

**Comment by kaveeshadinamidu** [comment]
Hey, @JooKS-me  may I create a pr with the fix?

**Comment by JooKS-me** [comment]
> Hey, @JooKS-me may I create a pr with the fix?

Yes, please :)
