### ISSUE TITLE
[BUG] Plugin location is wrong.

### ISSUE THREAD

**Issue by erdengk** [apache/incubator-shenyu-dashboard#187]
Plugin location is wrong.
![image](https://user-images.githubusercontent.com/37730787/157402004-80f25038-1354-479a-9a26-691267c8b651.png)

About reproducing the problem

I don't know how to reproduce it either, I had this problem after refreshing when I was using it. Refreshing again is still the same as above.

**Comment by daiwenyu** [comment]
i can fix it

**Comment by daiwenyu** [comment]
Sorry, I Cannot Reproduce. Can you explain the operation steps in detail?

**Comment by erdengk** [comment]
@daiwenyu 
In fact, I have no idea how to reproduce this. After one boot, it suddenly did.

**Comment by daiwenyu** [comment]
If it repeats again, create a new issues. thank you
