### ISSUE TITLE
do we have a release version to support copy rule in the dashboard

### ISSUE THREAD

**Issue by justlemontree** [apache/incubator-shenyu-dashboard#189]
do we have a release version to support copy rule in the dashboard? if not, do we have a roadmap?

**Comment by yu199195** [comment]
in master and 2.4.2，it support

**Comment by justlemontree** [comment]
OK, I find the cause, there are some wrong data ,  selector id in rule is not available in the selectlist got from backend.
otherwise, does this limit is too strict? I just want to copy the rule.

**Comment by yu199195** [comment]
> OK, I find the cause, there are some wrong data , selector id in rule is not available in the selectlist got from backend.
otherwise, does this limit is too strict? I just want to copy the rule.

 think copy data at the front , when save error data we should check it~

**Comment by justlemontree** [comment]
ok , got it.
